# -*- coding: utf-8 -*-
"""Atbash Cipher

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lh39RChDWU1qSoreOy27RF1Syme-KGGY
"""

# Atbash Cipher: Takes each letter from original word and replaces it with the letter in a flipped list of the alphabet that corresponds to the original letter's position in the original alphabet list
def Atbash_Cipher():
  print("ATBASH CIPHER")
  # original alphabet list
  alphabet_list = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
  # reversed alphabet list
  reversed_alphabet_list = []
  for x in reversed(alphabet_list):
    # append letters in reverse order to new reversed list
    reversed_alphabet_list.append(x)

  # take input from the user
  word = input("Enter a word/phrase to be encrypted with the Atbash Cipher: ")
  # iterate through every letter in the word
  encrypted_word_list = []
  for letter in word:
    # if there is a space
    if (letter == " "):
      # append space to new word list
      encrypted_word_list.append(" ")
    # if lowercase version of letter is present in the alphabet_list
    if (letter.lower() in alphabet_list):
      # assign the index of the lowercase version of the letter in the list to a variable called letter_index
      letter_index = alphabet_list.index(letter.lower())
      # create variable corresponding_letter which equals the letter in the reversed_alphabet_list which has the same index as the original letter in the original list
      corresponding_letter = reversed_alphabet_list[letter_index]
      # if letter is uppercase
      if (letter.isupper() == True):
        # append the uppercase leter to list by using .upper()
        encrypted_word_list.append(corresponding_letter.upper())
      else:
        # append lowercase letter
        encrypted_word_list.append(corresponding_letter)

  # convert the new word list into a string
  encrypted_word = ''.join([str(elem) for elem in encrypted_word_list])
  # handle exception of no inoput or integer input
  if (encrypted_word == ""):
    print("No valid encryption can be formed")
  else:
    print("The encrypted word/phrase is: ")
    print(encrypted_word)
    
Atbash_Cipher()
